# Generated by Django 5.2.15 on 2026-07-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catjitsu_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='deck',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
