# Generated by Django 5.2.15 on 2026-06-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catjitsu_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
