# Generated by Django 5.2.15 on 2026-06-19 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catjitsu_api', '0002_player_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='plays_as_one', to='catjitsu_api.player')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='plays_as_two', to='catjitsu_api.player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='won_the_match', to='catjitsu_api.player')),
            ],
        ),
    ]
