# Generated by Django 5.2.15 on 2026-07-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catjitsu_api', '0002_player_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='deck',
            field=models.CharField(max_length=16),
        ),
    ]
