# Generated by Django 5.2.15 on 2026-07-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catjitsu_api', '0003_alter_player_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_session_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='current_session_uuid_set_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
