# Generated by Django 5.2.15 on 2026-08-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catjitsu_api', '0004_player_current_session_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='nickname',
        ),
    ]
