# Generated by Django 5.2.15 on 2026-08-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catjitsu_api', '0006_add_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.CharField(blank=True, default='Apolito', max_length=200),
        ),
    ]
