# Generated by Django 5.2.15 on 2026-08-04 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catjitsu_api', '0008_add_language_screenreader'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='volume',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
