"""
Django settings for catjitsu_api project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.conf.global_settings import CSRF_TRUSTED_ORIGINS, STATIC_ROOT
from dotenv import load_dotenv

load_dotenv('.env.prod')

# 42 Oauth

# CLIENT_ID = ""
# CLIENT_SECRET = ""
CLIENT_ID = os.getenv("DJANGO_OAUTH_CLIENT_ID", "").split(",")
CLIENT_SECRET = os.getenv("DJANGO_OAUTH_CLIENT_SECRET", "").split(",")
REDIRECT_URI = "http://localhost:8000/auth/42/callback/"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework_api_key.permissions.HasAPIKey",
    ],
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-6!2s7zh4$dbjeh@j=n3a6%a-ye0*9h74%pa+*gvn-a380vwn32").split(",")
# SECRET_KEY = 'django-insecure-6!2s7zh4$dbjeh@j=n3a6%a-ye0*9h74%pa+*gvn-a380vwn32'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.getenv("DEBUG", default=1))
# DEBUG = True


ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
# ALLOWED_HOSTS = []
CSRF_TRUSTED_ORIGINS = os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "https://127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    'corsheaders',  # TEMPORARY: allow the Godot web build at http://localhost to access the API during local dev. Remove when frontend and API are served from the same origin.
    'rest_framework',
    'rest_framework_api_key',
    'rest_framework.authtoken',
    'catjitsu_api',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # TEMPORARY: short-circuits CORS for local development (remove when same-origin deployment is used)
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'catjitsu_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'catjitsu_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # TODO get variables for MariaDB connector from my.cnf
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'catjitsu_db',
    #     'USER':'api_rw',
    #     'PASSWORD':'1234',
    # }
    # Temporary SQLite alternative for systems without MariaDB
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings (TEMPORARY)
# Allow the Godot HTML5 export during local development at http://localhost to access this API.
# Remove these settings when the frontend is served from the same origin as the API.
CORS_ALLOWED_ORIGINS = [
    "http://localhost",
    "http://localhost:8060",
]

# If more permissive behavior is needed during dev, uncomment the following instead and remove before production:
# CORS_ALLOW_ALL_ORIGINS = True
